### ISSUE TITLE
Creating branches

### ISSUE THREAD

**Issue by rmbielby** [dfe-analytical-services/git-academy#9]
Cover the following tasks from the logbook: 

- Create a new branch in GitHub (<github_username>_main)
- Create a new branch in R-Studio (<github_username>_rstudio_stage_1)
- Create a new branch in Bash (<github_username>_git-bash_stage_1)

**Comment by Lsnaathorst1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Git academy - creating branches](https://trello.com/c/pXFoPKI4/1957-git-academy-creating-branches)
